.\"                                      Hey, EMACS: -*- nroff -*-
.TH AGISTUDIO 1 "August 25, 2012" "agistudio" "QT AGI Studio 1.3.0"
.SH NAME
QT AGI Studio \- an AGI adventure game development environment
.SH SYNOPSIS
.B agistudio
.RI [ options ]
.br
.SH DESCRIPTION
AGI (Adventure Game Interpreter) is the adventure game engine used by
Sierra On-Line(tm) to create some of their early games. \fBQT AGI Studio\fP
is a program that allows you to view, create and edit AGI games with
a friendly GUI.
.PP
.nf
The user interface is documented in HTML format, see
.fi
.nh
.IR /usr/share/agistudio/help
.hy
.SH OPTIONS
.TP
.B \-help
.br
Show of options.
.TP
.B \-dir GAMEDIR
.br
Open an existing game in GAMEDIR.
.SH SEE ALSO
.BR nagi(6),sarien(6),scummvm(6)
.IR
.SH AUTHOR
(C) 2003-2012 by Jarno Elonen <elonen@iki.fi>
