version: 1.3.0-{build}-{branch}
image: Visual Studio 2017
configuration: Release
clone_depth: 1
environment:
  QTDIR: C:\Qt\5.12.2\msvc2017_64\
install:
- ps: >-
    if (!(Test-Path -PathType Container build)) {
        Write-Host "Creating build folder... " -noNewLine
        New-Item -ItemType directory build | Out-Null
        Write-Host "OK" -foregroundColor Green
    }
before_build:
- ps: >-
    Set-Location build
    cmake -DQt5_DIR="$Env:QTDIR"\lib\cmake\Qt5 -G "Visual Studio 15 2017 Win64" ..
build:
  parallel: true
  verbosity: minimal
before_package:
- ps: ''
artifacts:
- path: build\src\$(CONFIGURATION)
  name: AGIStudio-$(APPVEYOR_BUILD_VERSION)